<?php
/*
Whitelist Tab
*/
defined ('IPV_URL') or die();

global $ipv_notices, $wpdb;

$ip = $this->get_ip();
$whitelist = get_option('ipv_whitelist');
$white_ips = array_keys( $whitelist );
$currentuser = wp_get_current_user();

if ( isset( $_GET['add_server_ip'] ) ) {

	$this->add_ip_to_whitelist($_SERVER['SERVER_ADDR'], $whitelist, $currentuser->user_login, 'Server address – generated by admin');
	$whitelist = get_option('ipv_whitelist');
	$white_ips = array_keys( $whitelist );
}

if ( !in_array( $_SERVER['SERVER_ADDR'], $white_ips ) ) {

	$ipv_notices[] = array(
		'msg' => __('Server address not found in whitelist. This may cause problems with scheduled tasks, such as WordPress update. <a href="'.$_SERVER['REQUEST_URI'].'&add_server_ip">Add now!</a>', 'ipv'),
		'classes' => 'warning'
	);
}



if ( isset( $_POST['kill_ip'] ) ) {

	$ip = stripslashes( $_POST['kill_ip'] );

	unset($whitelist[ $ip ]);
	update_option('ipv_whitelist', $whitelist);

	$this->maybe_update_htaccess($whitelist);

}


if ( isset( $_POST['add_ip'] ) ) {

	$ip = sanitize_text_field( preg_replace("/\s+/", "", $_POST['add_ip']) );

	$whitelist = $this->add_ip_to_whitelist($ip, $whitelist, $currentuser->user_login, $_POST['comment']);

	$this->maybe_update_htaccess($whitelist);

}
?>



		<div>
			<?php foreach ( (array) $ipv_notices as $key => $value ) : ?>
				<div class="notice notice-<?php echo $value['classes'] ?> is-dismissible">
					<p><?php echo $value['msg'] ?></p>
				</div>
			<?php endforeach; ?>
		</div>


		<p>List of IP addresses with unrestricted access.</p>

		<?php


		if (empty($whitelist)) {
			$whitelist[$ip] = array(
        'user' => $currentuser->user_login,
        'ip' => $ip,
        'auth' => 'Admin',
				'date_added' => current_time('mysql', true)
      );
		}

		// asort($whitelist);
		// print_r($whitelist);

		$cur_time = time();


		$users = get_users( array( 'fields' => array( 'ID' ) ) );

		// check for active sessions
		foreach($users as $user){
			$tokens = get_user_meta($user->ID, 'session_tokens');
			foreach ($tokens as $token) {
				foreach ($token as $key => $value) {
					if ($value['expiration'] - $cur_time > 0 && array_key_exists( $value['ip'], $whitelist ) ) {
						$whitelist[$value['ip']]['session'] = true;
					}
				}
			}
		}

		?>


			<table class="wp-list-table widefat fixed ips plugins">
				<thead>
					<tr>
						<th scope="col" id="ip" class="column-title">IP address</th>
						<th scope="col" id="location" class="column-location">Location</th>
						<th scope="col" id="user" class="column-registered">Registered by</th>
						<th scope="col" id="lastlogin" class="column-lastlogin hide-on-mobile">Comments</th>
					</tr>
				</thead>
				<tbody id="the-list">
				<?php
				foreach( $whitelist as $entry) {

					// $active = 'inactive';
					// if (isset($entry[$ip]['last_session'])) {
					//
					// $exp_time = @$entry['last_session']['expiration'];
					// $active = ( $exp_time - $cur_time > 0 ) ? 'active' : 'inactive';

					// if ( strpos($ip, $entry['ip']) == 1 ) $active = 'active';

					?>
					<tr class="<?php if ( !isset($entry['session']) ) echo 'in'; ?>active">
						<th class="check-column">
							<?php echo '<strong>' . $this->gdpr_ip($entry['ip']) . '</strong>'; ?>
							<div class="row-actions">
								<form method="post" class="submitbox">
									<input type="hidden" name="kill_ip" value="<?php echo $entry['ip'] ?>" />
									<input type="submit" class="button-link submitdelete" value="Remove" />
								</form>
							</div>
						</th>
						<td>
							<?php if (isset($entry['ipinfo'])) : ?>
							<?php if ( $entry['ipinfo']->city ) echo $entry['ipinfo']->city . ', ' ?>
							<?php $countryCode = isset($entry['ipinfo']->countryCode) ? $entry['ipinfo']->countryCode : 'N/A'; ?>
							<?php echo Locale::getDisplayRegion("-".$countryCode, get_locale()) ?>
							<div class="muted">
								<small>
									<?php echo $entry['ipinfo']->as ?>
								</small>
							</div>
							<?php endif; ?>
						<td>
						<?php
						$user = get_user_by('login', $entry['user']);
						// print_r($user);

						if ($user) echo '<a href="'.get_edit_profile_url().'?user_id='.$user->ID.'" title="User details">'.$user->display_name.'</a>';
						else echo $entry['user'];

						echo ' — ';
						printf(
			        __( '%s ago' ), human_time_diff( strtotime($entry['date_added']), $cur_time )
			      );


						 // echo '<pre>';
						 // print_r (get_user_meta($user->ID, 'session_tokens'));
						 // echo '</pre>';


							?>
						</td>
						<td class="column-lastlogin hide-on-mobile">
							<?php
							echo esc_attr($entry['auth']);
							// $getLastLogin = (get_user_meta($online->ID, 'last_login', true));
					    // $lastLogin = new DateTime($getLastLogin);
					    // $since_start = $lastLogin->diff(new DateTime(current_time('mysql', 1)));

							if ( isset($entry['last_session']) && isset($entry['last_session']['login']) ) {

								$log_time = $entry['last_session']['login'];
								if (isset($log_time)) {
									// print_r(@$entry['last_session']);
									echo '<br>Last session started ';
									echo human_time_diff( $log_time, $cur_time ) . ' ago';
									echo ' by '.$entry['last_session']['user'];
								}
							}
							?>
						</td>
					</tr>
				<?php } ?>
				</tbody>
			</table>

			<?php $this->gdpr_notice(); ?>


			<table class="form-table" role="presentation">
				<tbody>

					<tr>
						<th scope="row">Enter IP address
						</th>
						<td>
							<form action="" method="post">
									<input type="text"   name="add_ip" placeholder="0.0.0.0" value="" />
									<input type="text"   name="comment" placeholder="Comment (optional)" value="" size="50" />
									<input type="submit" class="button action" value="Add to Whitelist" />
							</form>
							<p class="description">Accepts IPv4 and IPv6 formats. <br>Partial addresses are allowed. e.g. <code>192.168.</code> will match the range from 192.168.0.0 – 192.168.255.255</p>
						</td>
					</tr>

				</tbody>
			</table>

	<?php
